---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: cluster-read-only
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list"]
    nonResourceURLs: []
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: colemick_cluster-read-only
subjects:
  - kind: User # May be "User", "Group" or "ServiceAccount"
    name: 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0#colemick@microsoft.com'
roleRef:
  kind: ClusterRole
  name: cluster-read-only
  apiVersion: rbac.authorization.k8s.io/v1alpha1
